import type { Knex } from "knex";

export async function up(knex: Knex): Promise<void> {
  if (await knex.schema.hasColumn("savings_accounts", "opening_request_hash"))
    return;
  await knex.raw(`
    DROP TRIGGER protect_final ON savings_deposits;
    ALTER TABLE savings_accounts
      DROP CONSTRAINT chk_savings_account_balance,
      DROP CONSTRAINT chk_savings_account_totals,
      DROP CONSTRAINT savings_accounts_check,
      DROP CONSTRAINT savings_accounts_check2,
      DROP COLUMN available_balance;
    ALTER TABLE savings_accounts
      ALTER COLUMN current_balance TYPE bigint USING round(current_balance*100)::bigint,
      ALTER COLUMN held_balance TYPE bigint USING round(held_balance*100)::bigint,
      ALTER COLUMN total_interest_earned TYPE bigint USING round(total_interest_earned*100)::bigint,
      ALTER COLUMN total_deposited TYPE bigint USING round(total_deposited*100)::bigint,
      ALTER COLUMN total_withdrawn TYPE bigint USING round(total_withdrawn*100)::bigint,
      ALTER COLUMN accrued_interest TYPE numeric(30,12),
      ALTER COLUMN ledger_entity_id DROP NOT NULL,
      ALTER COLUMN ledger_book_id DROP NOT NULL,
      ADD COLUMN available_balance bigint GENERATED ALWAYS AS (current_balance-held_balance) STORED,
      ADD COLUMN opening_sequence bigint GENERATED BY DEFAULT AS IDENTITY,
      ADD COLUMN opening_idempotency_key varchar(255),
      ADD COLUMN opening_request_hash char(64),
      ADD CONSTRAINT savings_account_opening_hash CHECK (opening_request_hash IS NULL OR opening_request_hash ~ '^[a-f0-9]{64}$'),
      ADD CONSTRAINT chk_savings_account_balance CHECK (current_balance>=0 AND held_balance>=0 AND held_balance<=current_balance AND available_balance>=0 AND accrued_interest>=0),
      ADD CONSTRAINT chk_savings_account_totals CHECK (total_deposited>=0 AND total_withdrawn>=0 AND total_interest_earned>=0),
      ADD CONSTRAINT savings_accounts_closed_zero CHECK (status<>'CLOSED' OR (closed_at IS NOT NULL AND current_balance=0 AND held_balance=0 AND accrued_interest=0));
    CREATE UNIQUE INDEX uq_savings_account_opening_idempotency ON savings_accounts(tenant_id,opening_idempotency_key) WHERE opening_idempotency_key IS NOT NULL;
    CREATE UNIQUE INDEX uq_savings_account_opening_sequence ON savings_accounts(opening_sequence);
    CREATE UNIQUE INDEX uq_savings_one_ordinary_account ON savings_accounts(tenant_id,customer_id,savings_product_id,currency) WHERE deleted_at IS NULL;

    ALTER TABLE savings_account_transactions
      DROP CONSTRAINT chk_savings_account_transaction_amount,
      DROP CONSTRAINT chk_savings_account_transaction_available_after,
      DROP CONSTRAINT chk_savings_account_transaction_available_balance,
      DROP CONSTRAINT chk_savings_account_transaction_available_before,
      DROP CONSTRAINT chk_savings_account_transaction_balance_after,
      DROP CONSTRAINT chk_savings_account_transaction_balance_before;
    ALTER TABLE savings_account_transactions
      ALTER COLUMN amount TYPE bigint USING round(amount*100)::bigint,
      ALTER COLUMN balance_before TYPE bigint USING round(balance_before*100)::bigint,
      ALTER COLUMN balance_after TYPE bigint USING round(balance_after*100)::bigint,
      ALTER COLUMN available_balance_before TYPE bigint USING round(available_balance_before*100)::bigint,
      ALTER COLUMN available_balance_after TYPE bigint USING round(available_balance_after*100)::bigint,
      ADD CONSTRAINT chk_savings_account_transaction_amount CHECK (amount>0),
      ADD CONSTRAINT chk_savings_account_transaction_available_after CHECK (available_balance_after>=0),
      ADD CONSTRAINT chk_savings_account_transaction_available_balance CHECK (available_balance_before<=balance_before AND available_balance_after<=balance_after),
      ADD CONSTRAINT chk_savings_account_transaction_available_before CHECK (available_balance_before>=0),
      ADD CONSTRAINT chk_savings_account_transaction_balance_after CHECK (balance_after>=0),
      ADD CONSTRAINT chk_savings_account_transaction_balance_before CHECK (balance_before>=0);

    ALTER TABLE savings_deposits DROP CONSTRAINT chk_savings_deposit_amount;
    ALTER TABLE savings_deposits
      ALTER COLUMN amount TYPE bigint USING round(amount*100)::bigint,
      ADD COLUMN request_hash char(64),
      ADD COLUMN ledger_journal_id uuid,
      ADD COLUMN ledger_request_hash char(64),
      ADD COLUMN ledger_posted_at timestamptz,
      ADD CONSTRAINT chk_savings_deposit_amount CHECK (amount>0),
      ADD CONSTRAINT savings_deposit_request_hash CHECK (request_hash ~ '^[a-f0-9]{64}$'),
      ADD CONSTRAINT savings_deposit_ledger_hash CHECK (ledger_request_hash IS NULL OR ledger_request_hash ~ '^[a-f0-9]{64}$'),
      ADD CONSTRAINT savings_deposit_success_evidence CHECK (status<>'SUCCESSFUL' OR (ledger_transaction_id IS NOT NULL AND ledger_journal_id IS NOT NULL AND ledger_request_hash IS NOT NULL AND ledger_posted_at IS NOT NULL AND processed_at IS NOT NULL));

    CREATE OR REPLACE FUNCTION savings_protect_deposit() RETURNS trigger LANGUAGE plpgsql AS $fn$
    BEGIN
      IF TG_OP='DELETE' THEN RAISE EXCEPTION 'Savings deposits cannot be deleted'; END IF;
      IF OLD.status='SUCCESSFUL' THEN RAISE EXCEPTION 'Successful savings deposits are immutable'; END IF;
      IF (NEW.tenant_id,NEW.id,NEW.savings_account_id,NEW.customer_id,NEW.amount,NEW.currency,NEW.operation_id,NEW.idempotency_key,NEW.request_hash)
         IS DISTINCT FROM
         (OLD.tenant_id,OLD.id,OLD.savings_account_id,OLD.customer_id,OLD.amount,OLD.currency,OLD.operation_id,OLD.idempotency_key,OLD.request_hash)
      THEN RAISE EXCEPTION 'Savings deposit command identity is immutable'; END IF;
      RETURN NEW;
    END $fn$;
    CREATE TRIGGER protect_final BEFORE DELETE OR UPDATE ON savings_deposits FOR EACH ROW EXECUTE FUNCTION savings_protect_deposit();

    CREATE OR REPLACE FUNCTION savings_validate_account() RETURNS trigger LANGUAGE plpgsql AS $fn$
    DECLARE v savings_product_versions%ROWTYPE;
    BEGIN
      IF TG_OP='UPDATE' THEN
        IF (NEW.tenant_id,NEW.id,NEW.customer_id,NEW.currency,NEW.savings_product_id,NEW.product_version_id,NEW.ledger_entity_id,NEW.ledger_book_id,NEW.ledger_account_id,NEW.opening_sequence,NEW.opening_idempotency_key,NEW.opening_request_hash)
           IS DISTINCT FROM
           (OLD.tenant_id,OLD.id,OLD.customer_id,OLD.currency,OLD.savings_product_id,OLD.product_version_id,OLD.ledger_entity_id,OLD.ledger_book_id,OLD.ledger_account_id,OLD.opening_sequence,OLD.opening_idempotency_key,OLD.opening_request_hash)
        THEN RAISE EXCEPTION 'Account identity/contract/ledger binding is immutable'; END IF;
        NEW.version=OLD.version+1;
      ELSE
        SELECT * INTO v FROM savings_product_versions WHERE tenant_id=NEW.tenant_id AND id=NEW.product_version_id FOR SHARE;
        IF NOT FOUND OR v.savings_product_id<>NEW.savings_product_id OR v.product_type<>'ORDINARY' OR v.currency<>NEW.currency OR v.status<>'PUBLISHED' OR NOT v.is_current OR now()<v.effective_from OR (v.effective_to IS NOT NULL AND now()>=v.effective_to)
        THEN RAISE EXCEPTION 'Account needs a current published ordinary product version'; END IF;
        IF NEW.held_balance<>0 OR NEW.current_balance<>0 THEN RAISE EXCEPTION 'Initial account balances must be zero'; END IF;
      END IF;
      RETURN NEW;
    END $fn$;
  `);
}

export function down(): Promise<never> {
  return Promise.reject(
    new Error("SV-02 ordinary-account migration is forward-only"),
  );
}
